services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      filebeat_collector: true

  db:
    image: postgres:latest # Changed from mysql
    environment:
      POSTGRES_DB: micro_videos # Changed from MYSQL_DATABASE
      POSTGRES_USER: postgres # Added default user
      POSTGRES_PASSWORD: root # Changed from MYSQL_ROOT_PASSWORD
    ports:
      - 5432:5432 # Optional: Expose postgres port if needed externally
    tmpfs:
      - /var/lib/postgresql/data # Added tmpfs for postgres data directory
    # security_opt: # This was likely specific to the previous mysql setup, usually not needed for postgres
    #   - seccomp:unconfined
