services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      filebeat_collector: true

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=micro_videos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    # security_opt: # Kept commented out, uncomment if needed and compatible
    #   - seccomp:unconfined

  # rabbitmq:
  #   build: ./.docker/rabbitmq
  #   ports:
  #     - 15672:15672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
